services:
  eureka-server:
    container_name: eureka-server
    platform: linux/amd64
    build:
      context: ./eureka-discovery-server
      dockerfile: Dockerfile
    ports:
      - '8888:8761'
    networks:
      - app-network


  config-server:
    container_name: config-server
    platform: linux/amd64
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - '9296:9296'
    depends_on:
      - eureka-server
    networks:
      - app-network
    environment:
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
  
  api-gateway:
    container_name: api-gateway
    platform: linux/amd64
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - '8080:9000'
    depends_on:
      - config-server
      - eureka-server
    networks:
      - app-network
    environment:
      - CONFIG_SERVER_URL=http://config-server:9296
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
      - ACCESS_TOKEN_SECRET_KEY:YwhN/Oo6+w7hY7OzlUcCsJHlDU92nLkIHKXOAdYfjEZ6R1u6gp0ZNMztUjNHtI7v4SHfvwMzk/JCKnVvd65C0w==
  
  
  auth-service:
    container_name: auth-service
    # image: auth-servicev
    platform: linux/amd64
    build:
      context: ./authentication-service
      dockerfile: Dockerfile
    ports:
      - '9002:9002'
    depends_on:
      - eureka-server
      - config-server
      - postgres_auth
      - api-gateway
    environment:
      - CONFIG_SERVER_URL=http://config-server:9296
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
      - ACCESS_TOKEN_SECRET_KEY:YwhN/Oo6+w7hY7OzlUcCsJHlDU92nLkIHKXOAdYfjEZ6R1u6gp0ZNMztUjNHtI7v4SHfvwMzk/JCKnVvd65C0w==
      - ACCESS_TOKEN_VALIDITY_SECONDS=3600
      - REFRESH_TOKEN_SECRET_KEY:YwhN/Oo6+w7hY7OzlUcCsJHlDU92nLkIHKXOAdYfjEZ6R1u6gp0ZNMztUjNHtI7v4SHfvwMzk/JCKnVvd65C0w==
      - REFRESH_TOKEN_VALIDITY_SECONDS=164000
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_auth:5432/auth_db
      - SPRING_DATASOURCE_USERNAME=auth_user
      - SPRING_DATASOURCE_PASSWORD=auth_password
      
    networks:
      - app-network

  employee-service:
    container_name: employee-service
    platform: linux/amd64
    build:
      context: ./employee-mgt
      dockerfile: Dockerfile
    ports:
      - '9001:9001'
    depends_on:
      - eureka-server
      - config-server
      - postgres_employee
      - api-gateway
      - auth-service
    environment:
      - CONFIG_SERVER_URL=http://config-server:9296
      - EUREKA_SERVER_URL=http://eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_employee:5432/employee_db
      - SPRING_DATASOURCE_USERNAME=employee_user
      - SPRING_DATASOURCE_PASSWORD=employee_password
    networks:
      - app-network


  postgres_auth:
    image: postgres
    container_name: postgres_auth
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_password
      POSTGRES_DB: auth_db
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
     - app-network


  postgres_employee:
    image: postgres
    container_name: postgres_employee
    environment:
      POSTGRES_USER: employee_user
      POSTGRES_PASSWORD: employee_password
      POSTGRES_DB: employee_db
    volumes:
      - employee_db_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - app-network

volumes:
  auth_db_data:
  employee_db_data:


networks:
  app-network:
    driver: bridge
