server:
  port: 9001
  forward-headers-strategy: framework
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  devtools:
    livereload:
      enabled: true
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:9296}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
