
CREATE TABLE department
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_department PRIMARY KEY (id)
);

CREATE TABLE employee
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name    VARCHAR(255) NOT NULL,
    last_name     VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    department_id BIGINT NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    updated_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_employee PRIMARY KEY (id)
);

ALTER TABLE employee
    ADD CONSTRAINT uc_employee_email UNIQUE (email);

ALTER TABLE employee
    ADD CONSTRAINT FK_EMPLOYEE_ON_DEPARTMENT FOREIGN KEY (department_id) REFERENCES department (id);

CREATE TABLE department_employees
(
    department_id BIGINT NOT NULL,
    employees_id  BIGINT NOT NULL,
    CONSTRAINT pk_department_employees PRIMARY KEY (department_id, employees_id)
);

ALTER TABLE department_employees
    ADD CONSTRAINT fk_depemp_on_department FOREIGN KEY (department_id) REFERENCES department (id);

ALTER TABLE department_employees
    ADD CONSTRAINT fk_depemp_on_employee FOREIGN KEY (employees_id) REFERENCES employee (id);