CREATE TABLE users
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username    VARCHAR(255)                            NOT NULL,
    password    VARCHAR(255)                            NOT NULL,
    employee_id BIGINT                                  NOT NULL,
    role        VARCHAR(255)                            NOT NULL,
    enabled     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_employee_id UNIQUE (employee_id);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);